version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    volumes:
      - static_volume:/home/deals/static
    depends_on:
      - web
    restart: "on-failure"
  web:
    build: .
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --no-input &&
                    gunicorn deals.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/microservice:rw
      - static_volume:/home/deals/static

    image: deals

    expose:
      - 8000
    restart: "on-failure"

volumes:
  static_volume:
